const {
  SHIPPING_LABEL_EMAIL_HTML,
  SHIPPING_KIT_EMAIL_HTML,
  ORDER_RECEIVED_EMAIL_HTML,
  DEVICE_RECEIVED_EMAIL_HTML,
  BLACKLISTED_EMAIL_HTML,
  FMI_EMAIL_HTML,
  BAL_DUE_EMAIL_HTML,
  DOWNGRADE_EMAIL_HTML,
  BLACKLISTED_LEGAL_HTML,
} = require('./emailHtml');

module.exports = {
  SHIPPING_LABEL_EMAIL_HTML,
  SHIPPING_KIT_EMAIL_HTML,
  ORDER_RECEIVED_EMAIL_HTML,
  DEVICE_RECEIVED_EMAIL_HTML,
  BLACKLISTED_EMAIL_HTML,
  BLACKLISTED_LEGAL_HTML,
  FMI_EMAIL_HTML,
  BAL_DUE_EMAIL_HTML,
  DOWNGRADE_EMAIL_HTML,
};
